config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships

  resources :beer_clubs

  resources :users

  resources :beers

  resources :breweries

root 'breweries#index'
get 'kaikki_bisset', to: 'beers#index'
get 'ratings', to: 'ratings#index'
get 'ratings/new', to:'ratings#new'
post 'ratings', to: 'ratings#create'
resources :ratings, only: [:index, :new, :create, :destroy]
resources :sessions, only: [:new, :create, :destroy]
get 'signup', to: 'users#new'
get 'signin', to: 'sessions#new'
delete 'signout', to: 'sessions#destroy'
resources :memberships, only: [:index, :new, :create, :destroy]
resources :places, only:[:index, :show]
post 'places', to: 'places#search'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
include RatingAverage
l = lambda{||Time.now.year}
 validates :year, numericality: { greater_than_or_equal_to: 1042,
                                    less_than_or_equal_to: l.call,
                                    only_integer: true }
 validates :name, presence: true
	has_many :beers, dependent: :destroy
	has_many :ratings, through: :beers
 def to_s
	return self.name	
 end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
    order = params[:order] || 'name'

    case order
      when 'name' then @breweries.sort_by!{ |b| b.name }
      when 'year' then @breweries.sort_by!{ |b| b.year }
    end

  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brewery }
      else
        format.html { render action: 'new' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year)
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Listing breweries</h1>

<p> Number of breweries: <%= @breweries.count %> </p> 

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= link_to 'Name', breweries_path(order:"name") %></th>
      <th><%= link_to 'Year', breweries_path(order:"year") %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
        <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brewery', new_brewery_path %>
<br/>
<%= link_to 'list of beers', beers_path %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

  <h2><%= @brewery.name %></h2>
	<em>Established in <%= @brewery.year %></em>

<p><strong>Number of beers:</strong><%=  @brewery.beers.count %></p>

<strong>Beers:</strong><br/>
 <% @brewery.beers.each do |beer| %>
   <%= link_to beer.name, beer %><br/>
 <% end %>

<% if @brewery.ratings.empty? %>
This brewery does not have ratings!
<% else %>
Has <%= pluralize(@brewery.ratings.count, 'rating')%>.
 <br/>Average rating:
 <%= @brewery.average_rating %>
<% end %>

<br/>

<%= link_to 'Edit', edit_brewery_path(@brewery) %> |
<%= link_to 'Back', breweries_path %>